################################################################################
# STEP 3: CLASSIFY ACTIVITY — SINGLE TAG DATASET
#
# PURPOSE
# Apply the proportional signal-change activity-classification framework to one
# MotusTagID × mfgID dataset created by Step 1.
#
# A MotusTagID × mfgID identifies a tag dataset rather than necessarily one
# biological individual. If a transmitter was redeployed, detections are divided
# into biological deployments using Band, Date_tagged, and Date_end from the
# deployment metadata.
#
# ACTIVITY CLASSIFICATION
# Activity is identified from:
#   • proportional signal change outside pooled receiver-type thresholds
#   • strongest-antenna switching
#   • strongest-receiver switching
#
# The shared classify_activity() function also applies signal-quality filtering,
# burst-interval validation, and isolated telemetry-dropout correction.
#
# OPTIONAL STATIONARY-TAG SCREEN
# A diagnostic screen can identify deployments showing extended inactivity near
# the end of the detection record. Users can choose whether this screen evaluates
# daytime, nighttime, or all detections depending on the biology of the study
# species.
#
# OUTPUTS
# For each biological deployment:
#   • classified detection table
#   • hourly activity table
#   • hourly activity summary
#   • diagnostic plots
#   • optional stationary-tag screening outputs
#
# IMPORTANT
# Edit Section 0 ("USER SETTINGS") before running the script.
################################################################################


# ==============================================================================
# 0) USER SETTINGS — EDIT THIS SECTION
# ==============================================================================


# ------------------------------------------------------------------------------
# TAG DATASET TO PROCESS
# ------------------------------------------------------------------------------

# Identify one Step 1 dataset using its MotusTagID, manufacturer ID, and
# dataset label.
#
# Step 3 automatically uses the most recent Step 1 download matching these
# identifiers.

target_MotusTagID <- "84746"

target_mfgID <- "160"

target_dataset_label <- "ExampleAllerton"


# ------------------------------------------------------------------------------
# INPUT DIRECTORIES AND METADATA
# ------------------------------------------------------------------------------

# Folder containing the MotusFiltered tag folders created by Step 1.

data_parent_dir <- here::here(
  "Sample_Data",
  "Interim",
  "Motus_Tower_Data_Filtered"
)


# Deployment metadata.
#
# Required fields include:
#   motusTagID
#   mfgID
#   Band
#   Date_tagged
#   Date_end
#   Lat
#   Lon
#   Burst_Interval
#
# Time_tagged is optional. If unavailable, deployment start time defaults to
# 00:00:00 on Date_tagged.

bird_metadata_path <- here::here(
  "Sample_Data",
  "Raw",
  "Metadata",
  "WOTH_IL_Metadata.csv"
)


# Receiver metadata.
#
# Required primary-system fields:
#   recvDeployName
#   DongleType_1
#   System1
#
# Optional second-system fields:
#   DongleType_2
#   System2
#   System1End

tower_metadata_path <- here::here(
  "Sample_Data",
  "Raw",
  "Metadata",
  "Tower_Metadata.csv"
)


# Folder containing the threshold summary generated by Step 2.

threshold_dir <- here::here(
  "Sample_Data",
  "Interim",
  "Motus_Tower_Data_Filtered"
)


# Step 2 threshold-summary filename pattern.

threshold_file_pattern <-
  "^all_birds_thresholds_summary_.*\\.csv$"


# ------------------------------------------------------------------------------
# OUTPUT DIRECTORY
# ------------------------------------------------------------------------------

processed_dir <- here::here(
  "Sample_Data",
  "Processed"
)


# ------------------------------------------------------------------------------
# TRANSMITTER AND HOURLY-COVERAGE SETTINGS
# ------------------------------------------------------------------------------

# Column in deployment metadata containing the programmed transmitter burst
# interval in seconds.

required_duty_cycle_col <- "Burst_Interval"


# Minimum fraction of expected transmission intervals required to retain an
# hourly activity estimate.
#
# Example:
# A 15-s transmitter produces approximately 240 expected detections per hour.
# At 0.25, an hour must contain at least 60 valid activity intervals.

sample_size_threshold <- 0.25


# Maximum timestamp difference used to identify detections belonging to the
# same transmitter burst.
#
# Multiple antennas or nearby receivers may record the same transmission at
# slightly different timestamps.

transmission_event_tolerance <- 0.3


# ------------------------------------------------------------------------------
# RECEIVER-SPECIFIC SIGNAL QUALITY
# ------------------------------------------------------------------------------

# Timing tolerance and minimum signal-to-noise ratio (SNR) used for each
# receiver type.
#
# These are the default values used in this study. Researchers applying the
# framework to other receiver systems may evaluate alternative values.

parameter_lookup <- tibble::tribble(
  ~DongleType_family, ~tolerance, ~S2N_cutoff,
  "FUNcube",                 0.3,           6,
  "RTL",                     0.3,          10,
  "SigmaEight",              0.3,          12
)


# ------------------------------------------------------------------------------
# MULTI-RECEIVER SITES
# ------------------------------------------------------------------------------

# Nearby receivers that represent one biological monitoring site.
#
# Receiver switching among receivers listed under the same site_id is retained
# as potential movement evidence, but detections from the full site are kept
# together rather than restricting the deployment to only one receiver.
#
# IMPORTANT:
# Researchers applying the framework elsewhere should modify this table to
# represent their own receiver network.
#
# If no receivers need to be grouped, use an empty table:
#
# multi_receiver_sites <- tibble::tibble(
#   site_id = character(),
#   recvDeployName = character()
# )

multi_receiver_sites <- tibble::tribble(
  ~site_id,   ~recvDeployName,
  "Allerton", "Allerton",
  "Allerton", "Allerton South",
  "Kennekuk", "Kennekuk 1",
  "Kennekuk", "Kennekuk 2",
  "Kennekuk", "Kennekuk 3",
  "Kennekuk", "Kennekuk 4",
  "Kennekuk", "Kennekuk 5",
  "Kennekuk", "Kennekuk 6",
  "Kennekuk", "Kickapoo"
)


# ------------------------------------------------------------------------------
# STATIONARY-TAG SCREEN
# ------------------------------------------------------------------------------

# Run the optional diagnostic screen for extended inactivity near the end of
# each biological deployment.

run_stationary_tag_screen <- TRUE


# Diel period used to evaluate extended inactivity.
#
# Choose ONE:
#
#   "day"
#     Use detections classified as day.
#     Appropriate when extended daytime inactivity would be unusual.
#
#   "night"
#     Use night_1 and night_2 detections.
#     Appropriate for primarily nocturnal species.
#
#   "all"
#     Use detections from all diel periods.
#
# Select a period during which the study species would normally be expected
# to show activity.

stationary_screen_timing <- "day"


# Number of hours preceding the final detection in the selected diel period
# used to evaluate extended inactivity.

stationary_late_window_hours <- 72


# Number of hours preceding the final detection in the selected diel period
# used to identify the focal receiver.

stationary_receiver_selection_hours <- 24


# Minimum number of valid signal-difference comparisons required
# within the screening window.

stationary_min_valid_late <- 30


# Minimum proportion of valid signal differences that must remain inside the
# receiver-specific inactivity threshold.

stationary_min_prop_within <- 0.80


# Maximum allowed mean absolute signal-strength difference, in dB.

stationary_max_mean_abs_sigdif <- 2.5


# Minimum proportion of detections in the receiver-selection window that must
# occur on the focal receiver.

stationary_min_receiver_prop <- 0.50


# ==============================================================================
# END USER SETTINGS
#
# Users should generally not need to edit anything below this point.
# ==============================================================================



# ==============================================================================
# 1) PROJECT ENVIRONMENT AND PACKAGES
# ==============================================================================

# Motus timestamps are stored in UTC.
# Local time is assigned explicitly from deployment coordinates later.

Sys.setenv(TZ = "UTC")


# ------------------------------------------------------------------------------
# Activate project-specific renv environment
# ------------------------------------------------------------------------------

if (file.exists(here::here("renv", "activate.R"))) {
  
  source(
    here::here(
      "renv",
      "activate.R"
    )
  )
  
} else {
  
  warning(
    "`renv/activate.R` was not found.\n",
    "Packages will be loaded from the default R library."
  )
}


# ------------------------------------------------------------------------------
# Required packages
# ------------------------------------------------------------------------------

required_packages <- c(
  "dplyr",
  "tidyr",
  "readr",
  "purrr",
  "lubridate",
  "stringr",
  "here",
  "lutz",
  "ggplot2",
  "scales",
  "suncalc",
  "conflicted"
)


package_available <- vapply(
  required_packages,
  requireNamespace,
  quietly = TRUE,
  FUN.VALUE = logical(1)
)


missing_packages <- required_packages[
  !package_available
]


if (length(missing_packages) > 0) {
  
  stop(
    "\nRequired package(s) are not installed:\n  ",
    paste(
      missing_packages,
      collapse = ", "
    ),
    "\n\nRun `renv::restore()` from the project root before running this script."
  )
}


invisible(
  lapply(
    required_packages,
    library,
    character.only = TRUE
  )
)


# ------------------------------------------------------------------------------
# Resolve common namespace conflicts
# ------------------------------------------------------------------------------

conflicted::conflict_prefer(
  "filter",
  "dplyr"
)

conflicted::conflict_prefer(
  "lag",
  "dplyr"
)

conflicted::conflict_prefer(
  "select",
  "dplyr"
)

conflicted::conflict_prefer(
  "first",
  "dplyr"
)

conflicted::conflict_prefer(
  "hour",
  "lubridate"
)

conflicted::conflict_prefer(
  "locale",
  "readr"
)


message(
  "✅ Required packages successfully loaded."
)



# ==============================================================================
# 2) LOAD SHARED FUNCTIONS
# ==============================================================================

activity_functions_file <- here::here(
  "Helper_Functions",
  "Activity_Timing_Functions.R"
)


plot_functions_file <- here::here(
  "Helper_Functions",
  "Diagnostic_Plots_Functions.R"
)


step3_functions_file <- here::here(
  "Helper_Functions",
  "Step_3_Shared_Functions.R"
)


required_function_files <- c(
  activity_functions_file,
  plot_functions_file,
  step3_functions_file
)


missing_function_files <- required_function_files[
  !file.exists(
    required_function_files
  )
]


if (length(missing_function_files) > 0) {
  
  stop(
    "Required helper-function file(s) were not found:\n  ",
    paste(
      missing_function_files,
      collapse = "\n  "
    )
  )
}


source(
  activity_functions_file
)

source(
  plot_functions_file
)

source(
  step3_functions_file
)


message(
  "✅ Shared activity, plotting, and Step 3 functions loaded."
)



# ==============================================================================
# 3) VALIDATE USER SETTINGS AND INPUTS
# ==============================================================================

# ------------------------------------------------------------------------------
# Validate selected tag identifiers
# ------------------------------------------------------------------------------

if (
  length(target_MotusTagID) != 1 ||
  is.na(target_MotusTagID) ||
  target_MotusTagID == ""
) {
  
  stop(
    "`target_MotusTagID` must contain one valid tag identifier."
  )
}


if (
  length(target_mfgID) != 1 ||
  is.na(target_mfgID) ||
  target_mfgID == ""
) {
  
  stop(
    "`target_mfgID` must contain one valid manufacturer identifier."
  )
}


if (
  length(target_dataset_label) != 1 ||
  is.na(target_dataset_label) ||
  target_dataset_label == ""
) {
  
  stop(
    "`target_dataset_label` must contain one dataset label."
  )
}


# ------------------------------------------------------------------------------
# Validate directories and metadata files
# ------------------------------------------------------------------------------

if (!dir.exists(data_parent_dir)) {
  
  stop(
    "Step 1 output directory was not found:\n  ",
    data_parent_dir
  )
}


if (!file.exists(bird_metadata_path)) {
  
  stop(
    "Deployment metadata file was not found:\n  ",
    bird_metadata_path
  )
}


if (!file.exists(tower_metadata_path)) {
  
  stop(
    "Receiver metadata file was not found:\n  ",
    tower_metadata_path
  )
}


if (!dir.exists(threshold_dir)) {
  
  stop(
    "Step 2 threshold directory was not found:\n  ",
    threshold_dir
  )
}


dir.create(
  processed_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


# ------------------------------------------------------------------------------
# Validate numeric settings
# ------------------------------------------------------------------------------

if (
  !is.numeric(sample_size_threshold) ||
  length(sample_size_threshold) != 1 ||
  is.na(sample_size_threshold) ||
  sample_size_threshold <= 0 ||
  sample_size_threshold > 1
) {
  
  stop(
    "`sample_size_threshold` must be a proportion greater than 0 and no greater than 1."
  )
}


if (
  !is.numeric(transmission_event_tolerance) ||
  length(transmission_event_tolerance) != 1 ||
  is.na(transmission_event_tolerance) ||
  transmission_event_tolerance < 0
) {
  
  stop(
    "`transmission_event_tolerance` must be one non-negative number."
  )
}


# ------------------------------------------------------------------------------
# Validate stationary-screen settings
# ------------------------------------------------------------------------------

valid_stationary_screen_timings <- c(
  "day",
  "night",
  "all"
)


if (
  run_stationary_tag_screen &&
  !stationary_screen_timing %in%
  valid_stationary_screen_timings
) {
  
  stop(
    "`stationary_screen_timing` must be one of: ",
    paste(
      valid_stationary_screen_timings,
      collapse = ", "
    )
  )
}


if (
  stationary_min_valid_late < 1
) {
  
  stop(
    "`stationary_min_valid_late` must be at least 1."
  )
}


if (
  stationary_min_prop_within < 0 ||
  stationary_min_prop_within > 1
) {
  
  stop(
    "`stationary_min_prop_within` must be between 0 and 1."
  )
}


if (
  stationary_min_receiver_prop < 0 ||
  stationary_min_receiver_prop > 1
) {
  
  stop(
    "`stationary_min_receiver_prop` must be between 0 and 1."
  )
}


message(
  "✅ User settings and input paths validated."
)



# ==============================================================================
# 4) LOAD AND PREPARE METADATA
# ==============================================================================

message(
  "📘 Loading deployment and receiver metadata..."
)


Bird_metadata <- readr::read_csv(
  bird_metadata_path,
  show_col_types = FALSE
)


Tower_metadata <- readr::read_csv(
  tower_metadata_path,
  locale = readr::locale(
    encoding = "latin1"
  ),
  show_col_types = FALSE
)


# ------------------------------------------------------------------------------
# Validate deployment metadata
# ------------------------------------------------------------------------------

required_bird_cols <- c(
  "motusTagID",
  "mfgID",
  "Band",
  "Date_tagged",
  "Date_end",
  "Lat",
  "Lon",
  required_duty_cycle_col
)


missing_bird_cols <- setdiff(
  required_bird_cols,
  names(
    Bird_metadata
  )
)


if (length(missing_bird_cols) > 0) {
  
  stop(
    "Deployment metadata are missing required column(s): ",
    paste(
      missing_bird_cols,
      collapse = ", "
    )
  )
}


Bird_metadata <- Bird_metadata %>%
  dplyr::mutate(
    motusTagID =
      as.character(
        motusTagID
      ),
    
    mfgID =
      as.character(
        mfgID
      )
  )


# ------------------------------------------------------------------------------
# Standardize receiver metadata
# ------------------------------------------------------------------------------

# This also converts optional all-NA System2/DongleType_2 columns to character,
# preventing logical-column errors when receivers have no second hardware era.

Tower_metadata <- standardize_tower_metadata(
  Tower_metadata
)


tower_long <- build_tower_eras(
  Tower_metadata
)


message(
  "✅ Deployment metadata and receiver eras prepared."
)



# ==============================================================================
# 5) LOAD STEP 2 THRESHOLDS
# ==============================================================================

message(
  "📊 Loading Step 2 threshold estimates..."
)


threshold_table <- load_threshold_table(
  threshold_dir =
    threshold_dir,
  
  threshold_file_pattern =
    threshold_file_pattern
)


tower_type_thresholds <- build_tower_type_thresholds(
  threshold_table =
    threshold_table,
  
  tower_long =
    tower_long
)


if (nrow(tower_type_thresholds) == 0) {
  
  stop(
    "No pooled receiver-type thresholds could be created from the Step 2 results."
  )
}


message(
  "✅ Pooled receiver-type thresholds prepared."
)


print(
  tower_type_thresholds
)



# ==============================================================================
# 6) FIND SELECTED STEP 1 DATASET
# ==============================================================================

data_dir <- find_latest_dataset_folder(
  data_parent_dir =
    data_parent_dir,
  
  target_MotusTagID =
    target_MotusTagID,
  
  target_mfgID =
    target_mfgID,
  
  target_dataset_label =
    target_dataset_label
)


ids <- parse_dataset_folder(
  data_dir
)


message(
  "\n📁 Using Step 1 dataset:\n  ",
  ids$folder_name
)


message(
  "   MotusTagID: ",
  ids$MotusTagID
)

message(
  "   mfgID: ",
  ids$mfgID
)

message(
  "   Dataset label: ",
  ids$dataset_label
)

message(
  "   Download date: ",
  ids$download_date
)



# ==============================================================================
# 7) PROCESS SELECTED TAG DATASET
# ==============================================================================

message(
  "\n🚀 Starting Step 3 activity classification..."
)


processing_result <- process_tag_dataset(
  data_dir =
    data_dir,
  
  Bird_metadata =
    Bird_metadata,
  
  tower_long =
    tower_long,
  
  tower_type_thresholds =
    tower_type_thresholds,
  
  parameter_lookup =
    parameter_lookup,
  
  multi_receiver_sites =
    multi_receiver_sites,
  
  processed_dir =
    processed_dir,
  
  required_duty_cycle_col =
    required_duty_cycle_col,
  
  sample_size_threshold =
    sample_size_threshold,
  
  transmission_event_tolerance =
    transmission_event_tolerance,
  
  run_stationary_tag_screen =
    run_stationary_tag_screen,
  
  stationary_screen_timing =
    stationary_screen_timing,
  
  stationary_late_window_hours =
    stationary_late_window_hours,
  
  stationary_receiver_selection_hours =
    stationary_receiver_selection_hours,
  
  stationary_min_valid_late =
    stationary_min_valid_late,
  
  stationary_min_prop_within =
    stationary_min_prop_within,
  
  stationary_max_mean_abs_sigdif =
    stationary_max_mean_abs_sigdif,
  
  stationary_min_receiver_prop =
    stationary_min_receiver_prop
)



# ==============================================================================
# 8) FINISH
# ==============================================================================

message(
  "\n🎉 STEP 3 COMPLETE"
)


message(
  "Processed tag dataset:\n  ",
  ids$folder_name
)


message(
  "Outputs saved under:\n  ",
  processed_dir
)


if (!is.null(processing_result)) {
  
  message(
    "✅ Activity classification completed successfully."
  )
}